IntroToASPNETCore/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntroToASPNETCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IntroToASPNETCore.Controllers
{//only Admin can access this page
    [Authorize(Roles = "Administrator")]
    public class ManageUsersController : Controller
    {
        //Inject the UserManager into the class
        private readonly UserManager<ApplicationUser> _userManager;

        public ManageUsersController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {//get the data for the roles
            var admins = await _userManager.GetUsersInRoleAsync("Administrator");
            var everyone = await _userManager.Users.ToArrayAsync();
            //pass all the admins and everyone else to a model and then pass that model to the View. 
            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };
            return View(model);
        }

    }
}

IntroToASPNETCore/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntroToASPNETCore.Models;
using IntroToASPNETCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IntroToASPNETCore.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        //this is just a private variable to use in the controller
        private readonly ITodoItemService _todoItemService;
        private readonly UserManager<ApplicationUser> _userManager;

        //this is the constructor of the controller, it is the first thing that runs when the class is called. We are passing all the  data from the service to the private variable.
        public ToDoController(ITodoItemService todoItemService, UserManager<ApplicationUser> userManager)
        {
            _todoItemService = todoItemService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();

            // todo Get to-do items from database
            var toDoItems = await _todoItemService.GetIncompleteItemsAsync(currentUser);

            // todo Put items into a model
            var model = new ToDoViewModel
            {
                Items = toDoItems
            };
            //todo Pass the view to a model and render
            return View(model);
        }

        public async Task<IActionResult> AddItem(NewToDoItem newItem)
        {
            if (!ModelState.IsValid) //if the model returns an error
            { //do stuff
                return BadRequest(ModelState);
            }
            //new check for user logged in
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Unauthorized();

            //check if the adding is successful (we still need to add AddItemAsync)
            bool IsSuccessful = await _todoItemService.AddItemAsync(newItem, currentUser);
            if (!IsSuccessful) //if it fails
            {
                return BadRequest(new { error = "Could not add item" });
            }
            //otherwise, if it works return OK result
            return Ok();
        }
        public async Task<IActionResult> MarkDone(Guid id)
        {
            //if there is no login then Bork
            if (id == Guid.Empty) return BadRequest();

            //if the current user is not the logged in then Bork
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Unauthorized();

            //if the update dien't work then Bork
            var successful = await _todoItemService.MarkDoneAsync(id, currentUser);
            if (!successful) return BadRequest();

            //otherwise everything is OK
            return Ok();
        }



    }

}

IntroToASPNETCore/Views/Shared/AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using IntroToASPNETCore.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{ //If the user is signed in the pass across the current user
    var currentUser = await UserManager.GetUserAsync(User);
    //if the current user is Admin and not null then return a True
    var isAdmin = currentUser != null
            && await UserManager.IsInRoleAsync(currentUser, Constants.AdministratorRole);
    //if there is an admin = true then load the code
    if (isAdmin)
    {
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-controller="ManageUsers" asp-action="Index">
                    Manage Users
                </a>
            </li>
        </ul>
    }
}

IntroToASPNETCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroToASPNETCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ToDo" asp-action="Index" class="navbar-brand">My ToDo List</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
                @await Html.PartialAsync("AdminActionsPartial")
            </div>

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - IntroToASPNETCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>